import Head from 'next/head'
import LogoGrid from '../components/LogoGrid'
import { builtFor } from '../data/builtFor'
import { workedFor } from '../data/workedFor'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LogoGrid title="I've built for" data={builtFor} />
        <LogoGrid title="I've worked for" data={workedFor} />
      </main>

    </div>
  )
}
